var popolari = {
    page: 1,
    results: [{
        adult: false,
        backdrop_path: "/4BtL2vvEufDXDP4u6xQjjQ1Y2aT.jpg",
        genre_ids: [28, 80, 53],
        id: 1419406,
        original_language: "zh",
        original_title: "捕风追影",
        overview: "",
        popularity: 491.2543,
        poster_path: "/uBRMTcpUd55pstCVTEn49uRuevX.jpg",
        release_date: "2025-08-16",
        title: "捕风追影",
        video: false,
        vote_average: 6.403,
        vote_count: 72
    }, {
        adult: false,
        backdrop_path: "/hpXBJxLD2SEf8l2CspmSeiHrBKX.jpg",
        genre_ids: [18, 27, 14],
        id: 1062722,
        original_language: "en",
        original_title: "Frankenstein",
        overview: "Il dottor Victor Frankenstein, uno scienziato geniale ma egoista, dà vita a una creatura in un mostruoso esperimento che porterà alla rovina sia del creatore che della sua tragica creazione.",
        popularity: 432.2216,
        poster_path: "/zxPLe88dEW3i2RTGAQixbKmZATz.jpg",
        release_date: "2025-10-17",
        title: "Frankenstein",
        video: false,
        vote_average: 7.809,
        vote_count: 1608
    }, {
        adult: false,
        backdrop_path: "/zpEWFNqoN8Qg1SzMMHmaGyOBTdW.jpg",
        genre_ids: [28, 53, 80],
        id: 1054867,
        original_language: "en",
        original_title: "One Battle After Another",
        overview: "Un gruppo di ex rivoluzionari si riunisce quando un loro perfido nemico riemerge dal loro passato, dopo sedici anni di silenzio. Il gruppo avrà il duro compito di salvare la figlia di uno di loro, prima che accada l'inevitabile.",
        popularity: 379.5305,
        poster_path: "/i9X9Yhwp53ndpyydMIIOrIXNS8m.jpg",
        release_date: "2025-09-23",
        title: "Una battaglia dopo l’altra",
        video: false,
        vote_average: 7.5,
        vote_count: 1501
    }, {
        adult: false,
        backdrop_path: "/7FDVhmCur4LMOfnXMteiSCtsdOb.jpg",
        genre_ids: [28, 12, 14],
        id: 1116465,
        original_language: "zh",
        original_title: "传说",
        overview: "Un archeologo notò che la consistenza delle reliquie scoperte durante lo scavo di un ghiacciaio assomigliava molto a un ciondolo di giada visto in uno dei suoi sogni. Lui e il suo team intraprendono quindi una spedizione nelle profondità del ghiacciaio.",
        popularity: 350.7234,
        poster_path: "/2eLjgesRLYQ8kjfwusSwxgNFcHv.jpg",
        release_date: "2024-07-05",
        title: "A Legend",
        video: false,
        vote_average: 6.555,
        vote_count: 82
    }, {
        adult: false,
        backdrop_path: "/5lQ4euO30sDin5nCifvi0vURFNd.jpg",
        genre_ids: [28, 35, 10751],
        id: 1248226,
        original_language: "en",
        original_title: "Playdate",
        overview: "Quando un contabile senza lavoro Brian accetta l'invito del padre casalingo Jeff per far giocare tra loro i figli, l'aspettativa è quella di un pomeriggio tranquillo. Invece, vengono inseguiti da dei mercenari e Brian deve sopravvivere a situazioni assurde. Un padre di periferia si ritrova coinvolto in un caos da film d'azione in questa divertente avventura.",
        popularity: 250.7214,
        poster_path: "/fGodXWqJkkkbSebPIlxLSygV8GY.jpg",
        release_date: "2025-11-05",
        title: "Playdate",
        video: false,
        vote_average: 6.308,
        vote_count: 224
    }, {
        adult: false,
        backdrop_path: "/sUoPlzchsCECqpm3ZmDPeL8QKDK.jpg",
        genre_ids: [28, 12, 27],
        id: 1084222,
        original_language: "en",
        original_title: "Operation Blood Hunt",
        overview: "",
        popularity: 278.5542,
        poster_path: "/wYf4Eq3c4iOa856tEwh3GHruHZW.jpg",
        release_date: "2024-12-12",
        title: "Operation Blood Hunt",
        video: false,
        vote_average: 6.809,
        vote_count: 34
    }, {
        adult: false,
        backdrop_path: "/4frrYwamVG0eXhdMTy3cpNNcCBp.jpg",
        genre_ids: [28, 18, 80, 53],
        id: 1128650,
        original_language: "zh",
        original_title: "誤判",
        overview: "Fok Chi-ho, poliziotto mosso da uno spiccato senso della giustizia, rassegna le proprie dimissioni dalle forze dell'ordine come forma di protesta, dopo l'assoluzione con formula piena di un criminale che aveva arrestato in flagranza di reato. Deluso dal sistema, Chi-ho decide di rimettersi a studiare per diventare avvocato e cercare di ristabilire la giustizia nelle aule dei tribunali. A partire dal caso di un povero giovane, ingiustamente accusato di traffico di stupefacenti.",
        popularity: 258.3819,
        poster_path: "/2tH6utnYvlTpGvbQCs5FdeQIKFp.jpg",
        release_date: "2024-12-08",
        title: "The Prosecutor",
        video: false,
        vote_average: 7.008,
        vote_count: 129
    }, {
        adult: false,
        backdrop_path: "/ebyxeBh56QNXxSJgTnmz7fXAlwk.jpg",
        genre_ids: [28, 878, 12],
        id: 1242898,
        original_language: "en",
        original_title: "Predator: Badlands",
        overview: "Nel futuro, su un pianeta remoto, un giovane Predatore, emarginato dal suo clan, trova un alleato improbabile in Thia e intraprende un viaggio pericoloso alla ricerca del nemico supremo.",
        popularity: 230.8365,
        poster_path: "/uhCp7eKGDTzMT5t3ibybcgeOCG9.jpg",
        release_date: "2025-11-05",
        title: "Predator: Badlands",
        video: false,
        vote_average: 7.407,
        vote_count: 386
    }, {
        adult: false,
        backdrop_path: "/wE1TZtB5G1fdiln3PPnnLhExuCz.jpg",
        genre_ids: [28, 53, 80],
        id: 1296504,
        original_language: "en",
        original_title: "Stand Your Ground",
        overview: "Jack, un ex operatore delle Forze Speciali, cerca vendetta dopo che sua moglie incinta viene uccisa durante un’invasione domestica motivata dall’odio. Uscito di prigione, Jack prende di mira un boss del crimine locale e la sua famiglia, scatenando una guerra brutale. Mentre le alleanze cambiano e la tensione cresce, Jack si prepara allo scontro finale.",
        popularity: 206.1248,
        poster_path: "/vKB59pPIYvjRxxEXoRoyUfaiBoD.jpg",
        release_date: "2025-05-09",
        title: "Stand Your Ground",
        video: false,
        vote_average: 4.809,
        vote_count: 47
    }, {
        adult: false,
        backdrop_path: "/iZLqwEwUViJdSkGVjePGhxYzbDb.jpg",
        genre_ids: [878, 53],
        id: 755898,
        original_language: "en",
        original_title: "War of the Worlds",
        overview: "Will Radford è un analista di sicurezza informatica di alto livello per la Homeland Security che monitora le potenziali minacce alla sicurezza nazionale attraverso un programma di sorveglianza di massa, finché un giorno un attacco da parte di un'entità sconosciuta lo porta a chiedersi se il governo gli stia nascondendo qualcosa... e al resto del mondo.",
        popularity: 184.2004,
        poster_path: "/vfYUXnQ1sNXxIm0DDiU6Vdmhz7i.jpg",
        release_date: "2025-07-29",
        title: "La guerra dei mondi",
        video: false,
        vote_average: 4.309,
        vote_count: 737
    }, {
        adult: false,
        backdrop_path: null,
        genre_ids: [],
        id: 1481331,
        original_language: "en",
        original_title: "Nahual",
        overview: "",
        popularity: 204.1363,
        poster_path: "/gQZn4Rx3LpIBnFunH1AKxAMYYd9.jpg",
        release_date: "2025-02-06",
        title: "Nahual",
        video: false,
        vote_average: 0,
        vote_count: 0
    }, {
        adult: false,
        backdrop_path: "/xmnqFHhGNYHf5JFy4GSfiIEG0ly.jpg",
        genre_ids: [80, 28, 18],
        id: 1429738,
        original_language: "th",
        original_title: "ตี๋ใหญ่ ฤกษ์ดาวโจร",
        overview: "Nella Bangkok degli anni '80, un astuto ladro compie una serie di audaci rapine, lasciando sgomenti le autorità e i cittadini... finché un poliziotto non decide di catturarlo.",
        popularity: 155.3802,
        poster_path: "/vqYZMLUwaN1z1iJ4TKvExyxo1TX.jpg",
        release_date: "2025-11-12",
        title: "Tee Yai: Born to Be Bad",
        video: false,
        vote_average: 5,
        vote_count: 25
    }, {
        adult: false,
        backdrop_path: "/7h0qCqkuQzmG5vXN3lGBc06reLd.jpg",
        genre_ids: [27, 53],
        id: 1468417,
        original_language: "en",
        original_title: "First Moon",
        overview: "",
        popularity: 145.787,
        poster_path: "/hcjYvv4k9qs0lDG1Q3GIglT30IW.jpg",
        release_date: "2025-05-06",
        title: "First Moon",
        video: false,
        vote_average: 4.486,
        vote_count: 35
    }, {
        adult: false,
        backdrop_path: "/gtKglOSEq3d4MgQE4VsrT1sRkd0.jpg",
        genre_ids: [16, 28],
        id: 1539104,
        original_language: "ja",
        original_title: "劇場版 呪術廻戦「渋谷事変 特別編集版」×「死滅回游 先行上映」",
        overview: "Un velo cala improvvisamente su Shibuya, nel bel mezzo dei festeggiamenti di Halloween, intrappolando all’interno numerosi civili. Satoru Gojo, il più forte degli stregoni, si getta nella mischia, ignaro che stregoni neri e spiriti maledetti tramano per imprigionarlo. Accompagnato dai compagni di classe e da altri stregoni di prima classe, Yuji Itadori si tuffa in uno scontro tra maledizioni senza precedenti: l’incidente di Shibuya.",
        popularity: 165.2137,
        poster_path: "/e2EWGvtko8mQD7HPA99KHysNQNN.jpg",
        release_date: "2025-11-07",
        title: "JUJUTSU KAISEN: Esecuzione",
        video: false,
        vote_average: 3.4,
        vote_count: 21
    }, {
        adult: false,
        backdrop_path: "/ufqytAlziHq5pljKByGJ8IKhtEZ.jpg",
        genre_ids: [53, 80, 9648],
        id: 425274,
        original_language: "en",
        original_title: "Now You See Me: Now You Don't",
        overview: "I maghi del crimine sono tornati! Al loro fianco, una nuova generazione di illusionisti riscrive le regole dello spettacolo con numeri mozzafiato, colpi di scena e sorprese che sfidano l’immaginazione. Un'esperienza visiva che sul grande schermo si trasforma in spettacolo puro.",
        popularity: 166.071,
        poster_path: "/a1xANzOxtnNpP2AE1PX2HLOgzzl.jpg",
        release_date: "2025-11-12",
        title: "L'illusione perfetta - Now You See Me: Now You Don't",
        video: false,
        vote_average: 6.266,
        vote_count: 188
    }, {
        adult: false,
        backdrop_path: "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
        genre_ids: [16, 28, 14, 53],
        id: 1311031,
        original_language: "ja",
        original_title: "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
        overview: "Lo scontro sta per raggiungere il suo apice! Chi ne uscirà vincitore?",
        popularity: 149.4179,
        poster_path: "/bq88RHSdnT2rpt4ki9CJUxHz2gH.jpg",
        release_date: "2025-07-18",
        title: "Demon Slayer: Kimetsu no Yaiba - Il Castello dell’Infinito",
        video: false,
        vote_average: 7.645,
        vote_count: 558
    }, {
        adult: false,
        backdrop_path: "/6zKjoOOb3OZnZuiHtQZn4Kd69Gq.jpg",
        genre_ids: [27, 53],
        id: 1197137,
        original_language: "en",
        original_title: "Black Phone 2",
        overview: "Quattro anni fa, il tredicenne Finn uccise il suo rapitore e riuscì a fuggire, diventando l’unico sopravvissuto a Il Rapace. Ma il vero male trascende la morte… e il telefono sta squillando ancora.",
        popularity: 143.9958,
        poster_path: "/2QpKUxbaXIuFtJZtiXCeWw2ZNcZ.jpg",
        release_date: "2025-10-15",
        title: "Black Phone 2",
        video: false,
        vote_average: 6.919,
        vote_count: 546
    }, {
        adult: false,
        backdrop_path: "/9QusGjxcYvfPD1THg6oW3RLeNn7.jpg",
        genre_ids: [28, 12, 14],
        id: 297802,
        original_language: "en",
        original_title: "Aquaman",
        overview: "Arthur è figlio di Tom, guardiano di un faro, e Atlanna, nientemeno che regina di Atlantide. L'unione dei due è però clandestina, tanto che per salvare il figlio Atlanna accetterà di farsi giudicare nella città subacquea, che la giustizierà consegnandola al più feroce dei popoli sottomarini. Arthur cresce imparando in segreto da Vulko, consigliere del re e di suo figlio Orm, i segreti di Atlantide, ma da adulto preferisce stare lontano dalla città sommersa e si limita a compiere gesta eroiche in mare, come salvare un sottomarino da un team di pirati. Qui finisce per lasciare morire uno di loro e il figlio giura vendetta, tanto da allearsi con il fratellastro di Arthur, Orm. Nel mentre la figlia di Re Nereus, Mera, cerca di convincere Arthur ad abbracciare il suo retaggio di regale atlantideo per scongiurare una guerra, ma per riuscire in questo piano sarà necessario ritrovare il perduto tridente di Atlan.",
        popularity: 128.4661,
        poster_path: "/ceYbmybt6ucJhM4lq6D998bMToc.jpg",
        release_date: "2018-12-07",
        title: "Aquaman",
        video: false,
        vote_average: 6.872,
        vote_count: 14573
    }, {
        adult: false,
        backdrop_path: "/2OHa6ukEq3Hce7Pc2kvu8wkmMFY.jpg",
        genre_ids: [28, 12, 53, 80, 18],
        id: 7451,
        original_language: "en",
        original_title: "xXx",
        overview: "Tatuato. Rasato a zero. Sper-muscoloso. Dall'aria spavalda e scostante. Una pubblicità ambulante per l'anti-autoritarismo. Estremo in ogni sua manifestazione, proprio come la lettera per cui inizia il suo nome... una lettera che porta tatuata sul collo in triplice copia. Xander Cage è XXX. Si guadagna da vivere in modo discutibile, vendendo in Internet video delle proprie bizzarre gesta.",
        popularity: 136.8627,
        poster_path: "/Add4kbQS39y5pgUOGZDC38Q146W.jpg",
        release_date: "2002-08-09",
        title: "xXx",
        video: false,
        vote_average: 6,
        vote_count: 4661
    }, {
        adult: false,
        backdrop_path: "/gqTz24ZRsCP6AKjARmEivY7m0cK.jpg",
        genre_ids: [16, 28, 10749, 14],
        id: 1218925,
        original_language: "ja",
        original_title: "チェンソーマン レゼ篇",
        overview: "Denji è diventato Chainsaw Man, il ragazzo con il cuore del demone Pochita, ed è entrato nella Quarta divisione speciale dei Devil Hunters. Dopo un appuntamento con Makima, la ragazza dei suoi sogni, Denji cerca riparo per la pioggia. Lì incontra Reze, una ragazza che lavora in un bar.",
        popularity: 116.2297,
        poster_path: "/A7J9KaSC3BYAqMoR0TKJXDbm0QX.jpg",
        release_date: "2025-09-19",
        title: "Chainsaw Man - Il film: La storia di Reze",
        video: false,
        vote_average: 7.795,
        vote_count: 212
    }],
    total_pages: 53780,
    total_results: 1075593
}



